version: 2.1
orbs:
  cypress: cypress-io/cypress@1.19.1
  aws-ecr: circleci/aws-ecr@6.8.1
workflows:
    test-and-deploy:
      jobs:
        - cypress/run:
            start: npm start
            wait-on: '-c .circleci/wait-on-config.json http://localhost:8080'
            post-steps:
              - store_test_results:
                  path: test-results
              - store_artifacts:
                  path: test-results
                  destination: test-results
        - aws-ecr/build-and-push-image:
            requires:
              - cypress/run
            context: aws-context
            repo: vspan
